#!/bin/bash -l
# Script to start interactive job on ARC systems

# Define color
RED='\033[0;31m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# User-provided arguments
original_args="$@"
# We'll add these
extra_args="--job-name='INTERACT'"

# System-specific defaults
case "${SYSNAME}" in
    tinkercliffs)
        def_partition="normal_q"
        def_gres=""
        ;;
    owl)
        def_partition="normal_q"
        def_gres=""
        ;;
    falcon)
        def_partition="v100_normal_q,t4_normal_q"
        def_gres="gpu:1"
        ;;
    *)
        echo "SYSNAME '${SYSNAME}' not recognized. Exiting."
        exit 1
        ;;
esac

# Print help if requested or if no argument is provided
if [[ " $original_args" == *" --help"* || $# -eq 0 ]]; then
  echo "Request an interactive job"
  echo "Usage: interact [OPTIONS]"
  echo "where OPTIONS are any valid Slurm (sbatch/salloc/srun) options, or:"
  echo "  --verbose     Print the Slurm command being run before starting job (for debugging purposes)"
  echo "  --help        Print this message"
  echo
  echo "To run, an account should be provided with -A [account] or --account=[account]. See 'quota' for a list of valid accounts and utilization metrics."
  exit
fi

# Add verbosity if requested
[[ " $original_args" == *" --verbose"* ]] && verbose=1 || verbose=0

# If account not specified by user
if [[ ! " $original_args" == *" -A"* && ! " $original_args" == *" --account"* ]]; then
  echo "An account must be specified with -A or --account. A list of valid allocation accounts (and remaining balances) can be found with the command 'quota'."
  exit 1
fi

# If partition not specified by user
if [[ ! " $original_args" == *" -p"* && ! " $original_args" == *" --partition"* ]]; then
  echo -e "${YELLOW} --- No partition specified:${NC} setting --partition=$def_partition"
  extra_args="--partition=$def_partition $extra_args"
fi

# If gres not specified by user (and def_gres not empty)
if [[ ! " $original_args" == *" --gres"* && ! -z $def_gres ]]; then
  echo -e "${YELLOW} --- No gres specified:${NC} setting --gres=$def_gres"
  extra_args="--gres=$def_gres $extra_args"
fi

# Command to be run
# Later arguments appear to be given priority so add user-provided
# arguments second on the off chance of conflicts
cmd="srun $extra_args $original_args --pty $SHELL"
# Print the command being run if user requested verbose mode
[[ $verbose -gt 0 ]] && echo "Running: $cmd"

# Print the warning message in red
echo -e "${RED} --- Warning:${NC} Your interactive session will consume resources - CPU cores, memory, and GPUs (on GPU nodes) while it remains open. Please close your session whenever you finish your work. Other users cannot use the resources allocated to your job until you close your session. Consider the use of batch jobs to optimize the resources allocation."

# Run
$cmd